### ISSUE TITLE
Binding for android

### ISSUE THREAD

**Issue by alt-ctrl-dev** [NicholasAStuart/myo-java-JNI-Library#5]
Hi @NicholasAStuart ,

Didn't mean to create an new issue, but there's no way for just having a common forum for each repo.

I wanted to know if the bindings you provided could be used for building an andoid library?

Cheer,
Reuben

**Comment by NicholasAStuart** [comment]
I don't intend to, as I'm not sure how to do it, and I believe the libraries Thalmic provides for PC/OSX won't work on android. They have their own library for Android, but I've not put in any effort to seeing if I could leverage this either.
